### ISSUE TITLE
Reduce minimum Python version to at least 3.10

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/virtual_rainforest_snakemake_template#21]
Currently the minimum is 3.11, because that's what I'm using, but 3.11 doesn't add any features I'm actually using in this repo. v3.10 would be a more sensible baseline. (While VR itself uses 3.9 as a minimum, 3.10 adds a more expressive way of writing union types, among other things, so it has some features I'd actually like.)

**Comment by davidorme** [comment]
I think there's a reasonable case for moving `vr` itself to 3.10+, given we're doing so much typing notation. And we could then use `match` but I don't think that is compelling by itself.

**Comment by alexdewar** [comment]
Pro-tip: pyupgrade is useful for this: https://github.com/asottile/pyupgrade

It also has a convenient pre-commit hook to make sure you're using new features.
